Only match delta in Lens if p2p enabled
morpho-dao/morpho-v1 pull request #1633
Opened 2023-01-04 12:48 UTC by Rubilmax

# Pull Request

## Issue(s) fixed

This pull request fixes an issue found in Yearn vaults

2023-01-04 20:40 UTC, pakim249CAL approved these changes

2023-01-05 08:48 UTC, MerlinEgalite requested changes
Blocking it for now for the reason mentioned above

2023-01-06 09:15 UTC, MerlinEgalite approved these changes

2023-01-06 09:16 UTC, MerlinEgalite commented
In fact, the lens has already been modified so we'll need to upgrade it anyway

2023-01-06 10:30 UTC, merged